import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import { NavbarWrapper } from "@/components/NavbarWrapper";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import { FooterWrapper } from "@/components/FooterWrapper";
import { useAuth } from "@/hooks/useAuth";
import ClientLayout from "@/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ChakraProvider>
            <ClientLayout>{children}</ClientLayout>
          </ChakraProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
